name: Application - Pull Request

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Docker Image
        run: |
          docker buildx create --name codbex-builder
          docker buildx use codbex-builder
          docker buildx build --tag ${{ inputs.application-name }} -o type=image --platform=linux/arm64,linux/amd64 .
