name: Application - Build

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string
      docker-registry:
        type: string
        default: ghcr.io
      docker-org:
        type: string
        default: codbex
      buildx-enabled:
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and Push Docker Image
        if: ${{ !inputs.buildx-enabled }}
        run: |
          docker build -t ${{ inputs.application-name }} .
          docker tag ${{ inputs.application-name }} ${{ inputs.docker-registry }}/${{ inputs.docker-org }}/${{ inputs.application-name }}:latest
          docker login ${{ inputs.docker-registry }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ inputs.docker-registry }}/${{ inputs.docker-org }}/${{ inputs.application-name }}:latest

      - name: Build and Push Docker Image (buildx)
        if: ${{ inputs.buildx-enabled }}
        run: |
          docker buildx create --name codbex-builder
          docker buildx use codbex-builder
          docker buildx build --tag ${{ inputs.application-name }} -o type=image --platform=linux/arm64,linux/amd64 .
          docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker buildx build --push --tag ghcr.io/${{ inputs.github-org }}/${{ inputs.application-name }}:latest -o type=image --platform=linux/arm64,linux/amd64 .
