name: Platform - Build

on:
  workflow_call:
    inputs:
      platform-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Set up JDK Corretto 20
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '20'
        architecture: x64

    - name: Maven Build
      run: mvn clean install
    - name: Integration tests
      run: mvn verify -Pintegration-tests

    - name: Build and Push Docker Image
      run: |
        docker buildx create --name codbex-builder
        docker buildx use codbex-builder
        cd application
        docker buildx build --tag ${{ inputs.platform-name }} -o type=image --platform=linux/arm64,linux/amd64 .
        docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker buildx build --push --tag ghcr.io/codbex/${{ inputs.platform-name }}:latest -o type=image --platform=linux/arm64,linux/amd64 .
